### PR TITLE
Update the RAM selections.

### PR DESCRIPTION
**Pull request by at88mph**

### CODE REVIEW

**Review by brianmajor — COMMENTED** [review]
Might as well make the assocated change (whatever it ends up being) on the helm side too.

**Review by sfabbro — COMMENTED** [review]
Looks good. I would add a few RAM slots around the threshold of 32GB where GPU users can select the V100 vs A100 nodes.
So would add: 26, 30, 36, 44 to the RAM choices.

**Comment by fraserw** [comment]
I wonder if adding a 0.5 GB ram option is possible? I have the rare headless task for which that value would be fine.

**Comment by at88mph** [comment]
I've added extra options for @sfabbro suggestions.  The current backend supports integers only, @fraserw, but if there is enough interest we could update the configuration code.

**Comment by fraserw** [comment]
Ah ok NVM. Mine was a pretty edge case.

**Comment by at88mph** [comment]
This need to get merged before closing.

**Review by sfabbro — APPROVED** [review]

**Pull request merged**
