### PR TITLE
[RFC][Testing] Attempt to add VSCode as a Session Container Type in VSCode

### PR DESCRIPTION
**Pull request by shionandrew**
[RFC][Testing] Attempt to add "vscode" as a Session Container Type in VSCode

I would like to add VSCode capabilities so that we can use a full-fledged development environment within CANFAR, to provide a nicer experience developing code where it will be run. 

I made this by pattern-matching on the skaha-notebook session type

---
**Server Startup**
This creates a code-server session listening on `localhost:8889` within the provided image:

`deployment/k8s-config/kustomize/base/skaha-workload/config/start-vscode-server.sh`
```
cd ${HOME}

code-server \
    --proxy-domain=session/vscode-server/"$1" \
    --disable-telemetry \
    --disable-update-check \
    --disable-workspace-trust \
    --bind-addr=0.0.0.0:8889
    /
```

---
**Config**
Added the following files by pattern-matching
* ingress-vscode-server.yaml
* launch-vscode-server.yaml
* service-vscode-service-yaml

---
**Skaha Service**
Modified the Skaha service to recognize `vscode-server` as a session type (`SESSION_TYPE_VSCODE_SERVER`) and made relevant changes.

---
**Image Requirements**
Must have [`code-server`](https://github.com/coder/code-server) installed

---
**NOTE**: This is not tested, and I'm not sure how I would go about testing this

### CODE REVIEW

**Comment by sfabbro** [comment]
There is a "contributed" session type where you can find a few VSCode-based containers. This feature is a bit hidden, but worth trying if you want to. Those sessions are containers based on code-server as well.  
Could you let us know if this enough, or you are may be looking at something different?

We may promote these kind of session if VSCode becomes more popular.

**Comment by shionandrew** [comment]
Thanks for letting me know–I’ve tried using one of those VSCode containers, but would also like to work inside of one of my pre-existing docker containers (which has packages installed with non-trivial dependencies). However, I was not able to install docker inside, e.g., `skaha/astroml-gpu-vscode:23.05`,  so I’m not sure the existing vscode-based containers would be enough for me, unless there is a way to run a docker image in those containers that I am not aware of. 

In general, I want to be able to develop within VSCode inside the environment in which the code will be run. Jupyter lab lacks many of the features in VSCode that I would like (e.g. an easy-to-use debugger, linting, an extension ecosystem), and having VSCode would be really helpful to my productivity. I’d really appreciate any help!

**Comment by brianmajor** [comment]
Hi @shionandrew - You should not need docker itself inside the container, unless you have a special case where your code is calling docker.  Also, as @sfabbro mentioned, you should just be able to use the 'contributed' type.  Here is the general idea:
1. Build your docker container locally (on your laptop) with vscode server and any other software installations you may need.  It has to conform to the rules of contributed images, namely:
- [listen on port 5000]
- [have any authentication disabled]
- [for *very* detailed info, see the 'contributed' files here:  https://github.com/opencadc/science-platform/tree/master/deployment/k8s-config/kustomize/base/skaha/config]
3. Push the image to images.canfar.net.  We can create a project for you for this purpose, unless you are a part of a project already?
4. Label the image (through the harbor ui at https://images.canfar.net as 'contributed')
5. Launch the container from the canfar portal.  It will show up there once labelled.

@sfabbro has made a base docker recipe for vscode here if you want to piggyback off of that:  https://github.com/opencadc/science-containers/blob/main/dockerfiles/Dockerfile.vscode

If I have totally misunderstood the intent his PR then please correct me! :)

**Comment by shionandrew** [comment]
Sorry for leaving this open for so long; the suggestion to use the 'contributed' type worked. Many thanks!

**Comment by brianmajor** [comment]
Great to hear @shionandrew

**Pull request closed without merging**
