### PR TITLE
Change default notebook launch options

### PR DESCRIPTION
**Pull request by sfabbro**
- **remove obsolete NotebookApp options**
- **change default directories for notebook sesssion, ensuring this would be located in runtime home directory**

### CODE REVIEW

**Comment by sfabbro** [comment]
This is to give a more familiar behaviour of jupyterlab for users, and it also would fix runtime install of jupyterlab extension (i.e. #301 ).

**Review by brianmajor — COMMENTED** [review]
@sfabbro - I guess we'll need to create the ~/.jupyter/lab/user-settings directories for users?  New users on allocate, and existing users manually...  Or does JupyterLab create those for you?

**Comment by sfabbro** [comment]
On my tests, JupyterLab creates them.

**Comment by brianmajor** [comment]
Looks good Seb.  If we make the same changes to the kustomize version of the files we'll be able to release this earlier.  Up to you.

- deployment/k8s-config/kustomize/base/skaha/config/launch-notebook.yaml
- deployment/k8s-config/kustomize/overlays/keel-dev/skaha/config/launch-notebook.yaml
- deployment/k8s-config/kustomize/base/skaha-workload/config/start-jupyterlab.sh

**Comment by sfabbro** [comment]
I think we can make it part of the larger release on CANFAR with the helm stuff.

**Comment by brianmajor** [comment]
Okay, merging this then...

**Review by brianmajor — APPROVED** [review]

**Pull request merged**
