### PR TITLE
Add Dockerfiles for CARTA v2 and v3 beta. Move existing CARTA v1.4 under v1

### PR DESCRIPTION
**Pull request by sefffal**
@brianmajor 
Here are the Dockerfiles etc. used to generate CARTA v2 and v3 beta images.
I tested them locally and on the science platform.

One remaining issue is that they are hardcoded to start the file browser in `/carta`. We should adjust this to start in a folder with e.g. soft links to the users home directory and the main projects directory on `arc`.

Thanks!

### CODE REVIEW

**Comment by brianmajor** [comment]
Thanks @sefffal !  A couple of initial comments/questions:

What is the difference between v2 and v3?  I presume v1 is the current 1.4 offering.

arcade-carta is no longer needed, just skaha-carta.

Also, you'll have to do another pull from opencadc master to get some changes I merged this morning related to our work yesterday.

**Comment by sefffal** [comment]
v2 is the current stable release, and v3 is from their beta channel. They are very similar images, except for the channel and package name installed. v3 has some nice additions that could be useful today, but I also hit a few small bugs while testing it out.

I'll make those fixes and update the PR.

**Comment by sefffal** [comment]
Ok, should be good to merge.

**Review by brianmajor — CHANGES_REQUESTED** [review]
Could you please just add a README.md to /v2 and /v3 with a single line showing how to run docker build?  This will help identify the version tag for the image.  For example:

`docker build -t images.canfar.net/skaha/carta::v3-betab -f Dockerfile .`

(or whatever it is)

**Comment by sefffal** [comment]
> Could you please just add a README.md to /v2 and /v3 with a single line showing how to run docker build? This will help identify the version tag for the image. For example:
> 
> `docker build -t images.canfar.net/skaha/carta::v3-betab -f Dockerfile .`
> 
> (or whatever it is)

Done.

**Review by brianmajor — APPROVED** [review]

**Pull request merged**
