### PR TITLE
Starting in HOME directory

### PR DESCRIPTION
**Pull request by sfabbro**
Two trivial fixes for notebook users:
- possibility for users to add jupyterlab options at runtime by setting the JUPYTERLAB_ARGS environment variable, i.e. `ENV JUPYTERLAB_ARGS="--debug"`.
- workaround to ensure the notebook terminal starts in the /arc/home/<user> (issue #140)

### CODE REVIEW

**Review by brianmajor — DISMISSED** [review]

**Comment by brianmajor** [comment]
I'm going to test this before merging.

**Comment by brianmajor** [comment]
A couple of things:
- Would it be better if the environment values were supplied at container launch time rather than at build time?  For headless sessions, environment can be passed in on launch with the `env=` param.  We could do that for the other sessions too.
- the cd $HOME trick seems to work
- The "$@" is passing the session ID to lupyter lab.  Jupyter lab thinks this is a ipynb file so fails.  If we go this way I think the "$@" has to be removed.

**Comment by brianmajor** [comment]
I just realized that my comment about dynamic environment setting is really part of a different discussion.  The var in the scripts would have to be there anyhow.
Another option for passing args to jupyter is to use an `arg=` param on the launch which might be a better match.

**Comment by sfabbro** [comment]
Yes doing it a runtime with an `env=` parameter would be even better (or both build and runtime). The UI would need to reflect this possibility too. Hopefully in this case users would not need to pass even more arguments through the "$@" item

**Comment by brianmajor** [comment]
> The "$@" is passing the session ID to lupyter lab. Jupyter lab thinks this is a ipynb file so fails. If we go this way I think the "$@" has to be removed.

@sfabbro -- you need to remove the "$@" from the script.

**Comment by sfabbro** [comment]
done

**Comment by brianmajor** [comment]
Thanks.

I don't see file `skaha-hook.sh` in this PR so I think that needs to be added.  What does it do?

**Comment by sfabbro** [comment]
skaha-hook.sh is not needed anymore. it used to do the "cd home".

**Comment by brianmajor** [comment]
Ah, sorry, misread the diff.

**Comment by brianmajor** [comment]
This is released now @sfabbro   Not sure if you built and pushed the new skaha notebook image, but since it only removed the hook there's no rush.

**Pull request merged**
