### PR TITLE
feat: allow setting nodeaffinity for apis and uis

### PR DESCRIPTION
**Pull request by at88mph**

### CODE REVIEW

**Comment by at88mph** [comment]
CADC-13796

**Review by shinybrar — CHANGES_REQUESTED** [review]
While the changes are consistent across all the different components, (cavern, posix-mapper, science-portal, skaha, and storage-ui) we need to add more documentation, either in the top level README under helm deployments, or in each deployment with Sample configurations of setting up node affinity and how it interacts with node labels

Is there a way we can test this, using helm test or some other form of testing in CI/CD before testing it on production / keel-dev?

**Comment by at88mph** [comment]
Will add documentation to the main `README.md`.

**Comment by at88mph** [comment]
Modified the Helm `README.md`.

Testing this might be best done by checking the `helm templates --debug` output with a `values.yaml` file to ensure that the supplied `nodeAffinity` markup is in place, or absent if none supplied.

```sh
$ helm template --debug --values <values.yaml> test-skaha ./deployment/helm/skaha
```

**Review by shinybrar — APPROVED** [review]
LGTM, ready to merge.

**Pull request merged**
